<a href="https://colab.research.google.com/github/momijizen/tensorflow-introduction/blob/main/L1_tensorflow_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing TensorFlow**


In [ ]:
%tensorflow_version 2.x # this line is not required unless you are in a notebook

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x # this line is not required unless you are in a notebook`. This will be interpreted as: `2.x`.


TensorFlow 2.x selected.


In [ ]:
import tensorflow as tf
print(tf.version) # make sure the version is 2.x

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


**Creating Tensors**

In [ ]:
string = tf.Variable("this is string ", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

print(string)
print(number)
print(floating)


<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is string '>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


**Rank/Degree of Tensors**

In [ ]:
rank1_tensor = tf.Variable(["Test", "os", "ok"], tf.string)
rank2_tensor = tf.Variable([["test", "ok", "os"], ["test", "yes", "os"]], tf.string)

print(rank1_tensor)
print(rank2_tensor)

<tf.Variable 'Variable:0' shape=(3,) dtype=string, numpy=array([b'Test', b'os', b'ok'], dtype=object)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=string, numpy=
array([[b'test', b'ok', b'os'],
       [b'test', b'yes', b'os']], dtype=object)>


To determine the rank of a tensor we can call the following method.

In [ ]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

**Shape of Tensors**
The shape of a tensor is simply the number of elements that exist in each dimension.

In [ ]:
rank2_tensor.shape

TensorShape([2, 3])

**Changing Shape**

The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.

In [ ]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1]) # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3,-1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                      # this will reshape the tensor to [3,2]

# The numer of elements in the reshaped tensor MUST match the number in the original

print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


**Slicing Tensors**

In [ ]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,9,0,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]
tensor = tf.Variable(matrix, dtype=tf.int32)
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [ ]:
# Now lets select some different rows and columns from out tensor
three = tensor[0,2] # selects the 3rd element from the 1st row
print(three)

row1 = tensor[0]  # selects the first row
print(row1)

column1 = tensor[:,0]   # selects the first column
print(column1)

row2and4 = tensor[1::2]   # selects second and fourth row
print(row2and4)

column1inrow2and3 = tensor[1:3, 0]
print(column1inrow2and3)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  9  0 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)
